templates/default-layout-wrapper.hamlet, templates/default-layout.hamlet
Closes #50
Pretty sure the spacing changes are correct; didn't actually test this though.
=> Convert all hamlet files to 2 space indentation

test/TestImport.hs
The Postgres equivalent to #53; see there for more details.
=> Postgres: wipe the database between tests

PROJECTNAME.cabal, test/TestImport.hs
The mongo equivalent of #53; see there for more details
~~(This doesn't have comments yet)~~
~~edit: there's alot of duplication going on running the database action. working on cleaning that up.~~
=> Mongo: wipe the database between tests

Add.hs, Application.hs, Foundation.hs, Home.hs, Main.hs, PROJECTNAME.cabal
=> Depend on yesod-core and import Yesod.Core in minimal

Foundation.hs, PROJECTNAME.cabal, test/Handler/CommonSpec.hs, test/TestImport.hs
There are two HLint suggestions I ignored, both around reducing duplication. I
want think a bit more about how to tackle those, or if it's even necessary.
I did not test-compile locally; there is a Travis suite that scaffolds and
test-compiles right?
=> HLint, use quasi-quoter

test/TestImport.hs
* Fixes Hlint unnecessary `$` warning
* Removes initial `do` from `wipeDB` function
=> Slight refactor of MySQL TestImport based off of #71

PROJECTNAME.cabal
FlexibleContexts is already in the list
=> add FlexibleInstances to extensions list

templates/homepage.hamlet
fixes https://github.com/yesodweb/yesod/issues/1049
=> Change test file location to test/Spec.hs

.travis.yml
@gregwebs This seemed to fix the travis issues.
=> Yesod test 1.5 max

config/settings.yml
See https://github.com/yesodweb/yesod/issues/1061
=> Document quoting numeric values

templates/homepage.hamlet
=> Added JSON Support example to the new page

templates/homepage.hamlet, templates/homepage.julius
=> prevent xss attack

Foundation.hs
also move it to the bottom since it won't be needed right away
=> explain HasHttpManager

PROJECTNAME.cabal, Settings.hs
=> remove CPP extension from cabal file

templates/homepage.hamlet
As requested [here](https://github.com/yesodweb/yesod/pull/1123)
=> suggest a test command based on Stack, see yesodweb/yesod#1018

Foundation.hs
* To help address https://github.com/yesodweb/yesod/issues/1246
=> Document recommended CSRF middleware usage

test/TestImport.hs
=> Change test runner to use useEnv instead of ignoreEnv

test/Handler/HomeSpec.hs
Follow up for #132
/cc @MaxGabriel
=> Fix indentation to be 4 spaces in HomeSpec

config/models
It is linked to this issue: https://github.com/yesodweb/yesod-scaffold/issues/144
=> Add a default=NULL to each Text Maybe column #144

test/TestImport.hs
Separated out from #156 since it applies to other DBs too.
=> Make test detect incorrect foreign-key checking status in wipeDB

src/Foundation.hs, src/Handler/Home.hs, templates/homepage.hamlet, test/TestImport.hs
=> Add `DB` type alias

package.yaml
=> Update test-suite name to PROJECTNAME-test

src/Model.hs
The upcoming version of persistent-template will require these https://github.com/yesodweb/persistent/pull/1002
cc @parsonsmatt
=> Add DerivingStrategies and StandaloneDeriving for persistent
