yesodweb/yesod-scaffold

test/TestImport.hs
Initial implementation of wiping the database for the MySQL backend (I guess I'll end up doing 1 PR per-backend?). Based on testing this works fine, though [the logs](https://gist.github.com/MaxGabriel/87d5ca66a0959df1e761) are a little wonky; sometimes it seems to be missing the last few SQL statements from a test in the logs. For example, these logs are missing the `TRUNCATE TABLE user` and `SET foreign_key_checks = 1` queries:
```
11/Jan/2015:21:14:41 -0800 [Debug#SQL] "SHOW TABLES;" [] @(persistent-2.1.1.3:Database.Persist.Sql.Raw ./Database/Persist/Sql/Raw.hs:42:26)
11/Jan/2015:21:14:41 -0800 [Debug#SQL] "SET foreign_key_checks = 0;" [] @(persistent-2.1.1.3:Database.Persist.Sql.Raw ./Database/Persist/Sql/Raw.hs:64:18)
11/Jan/2015:21:14:41 -0800 [Debug#SQL] "TRUNCATE TABLE email" [] …
```
=> MySQL: wipe the database between tests

test/TestImport.hs
This PR wipes the database between tests in SQLite. Unfortunately, this PR is more complex than the MySQL, Postgres, or Mongo ones (see the comments in the code itself for details). Those comments also aren't great because I'm really tired right now.
Still, I wanted to get up something for people to look at.
=> Wipe the database between tests in SQLite

templates/default-layout-wrapper.hamlet
(ChromeFrame has been deprecated for a year or so)
=> Remove ChromeFrame link from scaffolding; closes #60

PROJECTNAME.cabal, test/Handler/HomeSpec.hs
yesod-test 1.4.3 adds `addToken` and deprecates `addNonce`. This switches to the new version.
=> Switch from addNonce to addToken; fixes deprecation warning

static/css/bootstrap.css
The bootstrap.css have one line , defined an not exist css.map file
Delete the last line to prevent 404 request
See https://github.com/yesodweb/yesod/issues/934
=> Fix css.map 404 for postgres branch

templates/homepage.hamlet, templates/homepage.lucius
This pull makes some small style improvements to the "Welcome To Yesod!" homepage that's generated by default.
* Tweaked font size and line spacing.
* Added horizontal rules to separate form example.
* Gave form input and h1 some breathing room.
* Aligned footer.
Before:
After:
=> Improve styles for generated homepage

PROJECTNAME.cabal
Two upper bounds in the generated scaffolding conflicted with the latest Stackage snapshot - relaxing them appears to work fine (tested in the sqlite and MySQL versions)
=> Relax version bounds

.ghci
This file was out of date with the cabal file's extensions list. The missing
extensions were:
- NoImplicitPrelude
- NoMonomorphismRestriction
- RecordWildCards
- TupleSections
- ViewPatterns
I find the multi-line format much easier to manage. It does have a minor 
impact on startup time:
Single-line:
% time echo ':exit' | ghci
...
ghci  0.23s user 0.02s system 98% cpu 0.246 total
Multi-line:
% time echo ':exit' | ghci
...
ghci  0.32s user 0.02s system 99% cpu 0.342 total
If this is unacceptable, let me know and I'll join it back up.
=> Add missing extensions to .ghci, re-format as multi-line

Foundation.hs
Potential solution for yesodweb/yesod#985
I think that adding a comment with the exact text of the type synonyms is just as good for discoverability as making the type synonyms directly from the scaffolding. It also avoids the hassle of adding another function or making a breaking change.
Thoughts?
=> Document that mkYesodData generates the Handler and Widget type synonyms

Foundation.hs
Response to https://github.com/yesodweb/yesod/issues/1009.
I'm not sure what behavior the scaffolding should have. I just kept it very simple.
=> Replaced deprecated `getAuthId` with `authenticate`

config/keter.yml
As added in [yesodweb/yesod/#970](https://github.com/yesodweb/yesod/pull/970)
=> Document 'copy-to-args' option in keter.yml

config/keter.yml
Without a trailing slash, the bundle might be written to a *file* named `incoming` if the `incoming` directory doesn't exist.
=> Add trailing slash to example 'copy-to' destination in keter.yml

.gitignore
Hi,
It seems with this issue (https://github.com/commercialhaskell/stack/issues/247) that the `.stack-work` directory should be in the `.gitignore` file? Am I right?
Tell me if it's not the case and if there are other stack related files to add to the `.gitignore` file.
Thanks.
=> core(gitignore): add stack work to gitignore

stack/postgres.yaml
travis can curl for postgres's stack
Probably should instead have a concept of ignored files
=> hack to get the .travis.yml to work on a branch

PROJECTNAME.cabal, Settings.hs
This PR would enable MySQL's strict mode for connections coming from the application. This causes MySQL to raise errors instead of silently truncating too-long data, among other changes. This PR would have prevented https://github.com/yesodweb/persistent/issues/122.
Current wiki page about this: https://github.com/yesodweb/persistent/wiki/Database-Configuration#strict-mode
=> Enable MySQL strict mode from the scaffolding

.travis.yml, Application.hs, PROJECTNAME.cabal, test/TestImport.hs
Integration tests will perform application logging to stdout
This means you can actually figure out why your tests are failing.
A downside is a lot of output interleaved with your tests.
We should address that downside in a future change.
I already have something working locally that I want to try out
for a few weeks and refine a bit.
=> upgrade to yesod-test-1.5

Application.hs, Foundation.hs, Handler/Comment.hs, Handler/Home.hs, Model.hs, PROJECTNAME.cabal, config/models, config/routes, templates/default-layout-wrapper.hamlet, templates/homepage.hamlet, templates/homepage.julius, templates/homepage.lucius, test/Handler/CommentSpec.hs
In #73 there was some discussion about adding an example of using Yesod as an API server. I took a quick stab at that; this PR just adds a link you can click on the homepage, which triggers an AJAX request to the server to create a new user. The server inserts the user into the database and returns the data to the client, which updates adds the user to an `<ul>`.
Is this roughly what we're looking for? I wrote functions to request all users and to delete specific ones as well, if we want to add more API server example code.
=> Draft of using Yesod as an API server to a Javascript frontend

config/settings.yml
* Would help address the confusion here: https://github.com/yesodweb/yesod/issues/1109
Should `wai-devel` be mentioned here as well?
=> Warn that `port` in settings.yml isn't for yesod devel

test/Handler/CommentSpec.hs
The `Handler.Comment` specs fail, because of a call to `addTokenFromCookie`,
but no `defaultCsrfMiddleware` on `Foundation.hs` [1]
This removes all calls to `addTokenFromCookie` from the yesod templates'
tests.
This closes commercialhaskell/stack-templates#71 and is related to PR
commercialhaskell/stack-templates#72.
[1] - https://github.com/commercialhaskell/stack-templates/blob/master/yesod-postgres.hsfiles#L289
Also could be fixed with as mentioned in commercialhaskell/stack-templates#71:
```
-    yesodMiddleware = defaultYesodMiddleware
+    yesodMiddleware = defaultYesodMiddleware . defaultCsrfMiddleware
```
=> Patch templates so they don't require CSRF

test/Handler/HomeSpec.hs
Diff is big, but it simply adds the missing `describe "Homepage" $ do`
=> Add missing describe statement

Application.hs, Foundation.hs, Handler/Profile.hs, PROJECTNAME.cabal, Settings.hs, config/routes, config/settings.yml, config/test-settings.yml, templates/homepage.hamlet, templates/profile.hamlet, test/Handler/ProfileSpec.hs, test/TestImport.hs
PR does a bunch of closely related stuff:
1. Add `appDevelopment` setting
1. Add auth dummy login, whenever in development mode
1. Add a route that can be access only by authenticated user. While doing so, also make each route's authorization explicit
1. Extend the tests to show how to login a user
Homepage:
Profile page (authenticated user):
btw, to confirm there isn't a better way - I had to scaffold to another directory, do the changes, and then copy back to this repo. 
Also, there doesn't seem to be a `stack test` in this repo - is there a way to properly check my code ?
=> Add auth Dummy in development mode

Application.hs, PROJECTNAME.cabal
Here are the changes to the *mysql scaffolding only* for thread-safe use of the mysql library, further to #139 .
This will very shortly be accompanied by a PR to add a blog post to yesodweb.com-content.  That post is meant to provide the documentation, so the comments in the code simply refer to it.
The conditional compilation and other baggage needed to define forkOSWithUnmask for base<4.9.0 is an absolute pain :-(
=> Use mysql library in a thread-safe manner

config/models
On some MySQL versions, Text fields cannot be NULL and display the following message:
> BLOB/TEXT column 'password' can't have a default value
This pull request solves that.
=> Setting Text fields to be varchar(255) in MySQL

src/Foundation.hs
Otherwise, routes with params didn’t work (e.g. `/user/#UserId`). We would get the error:
```
$ src/Foundation.hs:58:1: error:
Illegal view pattern:  fromPathPiece -> Just dyn_amz5
Use ViewPatterns to enable view patterns
```
=> Add `ViewPatterns` to allow routes with params

package.yaml, test/TestImport.hs
This applies to sqlite only.  Fixes #155
=> Fix foreign key setting in tests for persistent-sqlite >= 2.6.2

templates/default-layout-wrapper.hamlet
This template includes only the `bootstrap.css` file, so lines like the following doesn't work. This is from the `default-layout.hamlet` that comes with the template:
<button type="button" .navbar-toggle.collapsed data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
To solve this I put a `<script src="...` in the `default-layout-wrapper.hamlet`, so it gets the `bootstrap.js` from a CDN.
=> Added bootstrap.js from a CDN to make navbar collapse and uncollapse to work.

templates/default-layout-wrapper.hamlet
The replaced one was deprecated (https://support.google.com/analytics/answer/1205784?hl=en#Notes).
The `_trackPageLoadTime` parameter seems to be not needed anymore and that will be ignored in the future. So I changed the tracking code to the default suggested in the Google Analytics documentation (https://developers.google.com/analytics/devguides/collection/analyticsjs/tracking-snippet-reference).
=> Updated Google Analytics tracking code.

app/Main.hs
An issue with the current scaffolding is that `PROJECTNAME_LOWER` isn't replaced correctly. If you run:
`stack new test-keys yesod-postgres`
then you'll get output like this in the `settings.yml` file:
```
user:     "_env:PGUSER:test-keys_LOWER"
password: "_env:PGPASS:test-keys"
```
I'm pretty sure what's going on is that `PROJECTNAME` is being replaced first, so then the replace for `PROJECTNAME_LOWER` doesn't work.
I also see there's a [`to-stack-templates.sh`](https://github.com/yesodweb/yesod-scaffold/blob/master/to-stack-templates.sh) file that appears to implement this behavior, but I can't find it referenced anywhere in this repo. Possibly it's unused and can be deleted? 
This change is untested, but I think you can just look at the changed code and tell whether or not it's the …
=> Replace PROJECTNAME_LOWER before PROJECTNAME

app/Main.hs
This is required to solve the issue in #137.
I wrote out a generalized version of this as well, that would take any file with two underscores, remove the old file without two underscores, then rename the double unscored file to remove the underscores. This seemed like too much complexity to be worth it though, since I think this would only apply to a handful of files ever (mostly CI service files).
=> Allow adding a __.travis.yml file that will become .travis.yml for the end user

config/models, config/routes
Since the routes and models files have a custom syntax, I thought it'd be nice to link to the files for the syntax for them.
For the routes file I don't think it's super important, but it's a nice to have (routing is simple, explained in full by the Yesod book, and has limited options). The models syntax though has extensive configuration options and is hidden away, so it's more important to link to it.
=> Link to Template Haskell syntax for models and routes file

README.md
Addresses part of #137 
I think a README would be a really good addition to the scaffolded project. It would help new users get started, and provide a foundation of documentation for adding other people to your project. IIRC, generating a README is pretty standard other scaffoldings I've seen.
Suggested additions or changes to this README are welcome.
The only potential hassle here is providing database-specific setup instructions.
=> Add README to scaffolded project

package.yaml
Right now, you get this error when you build:
```
[1 of 3] Compiling DevelMain        ( app/DevelMain.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/todo/todo-tmp/DevelMain.o ) [Foreign.Store changed]
/home/sibi/todo/app/DevelMain.hs:40:1: error:
Could not find module ‘Foreign.Store’
Perhaps you meant
Foreign.Ptr (from base-4.10.1.0)
Foreign.Safe (from base-4.10.1.0)
Foreign.Storable (from base-4.10.1.0)
Use -v to see a list of the files searched for.
|
40 | import Foreign.Store
| ^^^^^^^^^^^^^^^^^^^^
```
My PR just adds the appropriate package in the package.yaml file.
=> Add foregin-store: Fix compile error for lts-10

src/Application.hs
As soon as you add a new route which accepts an input, you will be
greeted with this error:
```
/home/sibi/todo/src/Application.hs:49:1: error:
Illegal view pattern:  fromPathPiece -> Just dyn_awHr
Use ViewPatterns to enable view patterns
|
49 | mkYesodDispatch "App" resourcesApp
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
And since defining a route taking inputs is a common task, we should
add this extension by default in the file.
=> Add ViewPatterns to Application.hs

src/Foundation.hs
Since MonadIO implies `m` is a `Monad`, and all `Monad`s are `Functor`s, the constraint is unnecessary.
=> Remove Functor constraint from DB synonym

src/Foundation.hs
This PR enables the InstanceSigs extension to provide type annotations on the type classes in Foundation.
Types are the best documentation, so we might as well put them there :smile:
=> Add type signatures to instances in Foundation

README.md
The `createuser` command in the readme did not work for me.  The `--password` option is for the user running the create command, not the password for the user being created:
```
-W
--password
Force createuser to prompt for a password (for connecting to the server, not for the 
password of the new user).
This option is never essential, since createuser will automatically prompt for a 
password if the server demands password authentication. However, createuser will 
waste a connection attempt finding out that the server wants a password. In some 
cases it is worth typing -W to avoid the extra connection attempt.
```
I don't think there is any way to supply the new user password in the command, so I am suggesting `--pwprompt`:
```
-P
--pwprompt
If given, createuser will issue a prompt for …
```
=> Postgres createuser command in README

app/Main.hs
I wanted to be able to create module names based on the project name.  `stack new` already supports this through `{{name-as-module}}`.  When name is `my-project`, name-as-module is `Myproject`.  This change uses `PROJECTNAME_MODULE` as the placeholder for this variable.
I tried out this change and the postgres branch built fine using this new placeholder as a module name, file name, and directory name.
=> Support {{name-as-module}} via PROJECTNAME_MODULE

test/TestImport.hs
If a user enables the `pg_stat_statements` Postgres extension, they will be met with the following error when they try to run their tests:
```
uncaught exception: SqlError SqlError {sqlState = "42809", sqlExecStatus
= FatalError, sqlErrorMsg = "\"pg_stat_statements\" is not a table",
sqlErrorDetail = "", sqlErrorHint = ""}
```
For the purposes of wiping the test database before each test run, I believe the user is only interested in the tables of type `BASE TABLE`.
=> Only fetch tables of type 'BASE TABLE' in tests

test/TestImport.hs
I think the vast, vast majority of yesod-scaffold users will never grow to the size where they need to care about this. But for the handful that do, it should save them a lot of time dredging through stackoverflow and postgres mailing lists about this.
I could have made a wiki page about this and cleaned it all up, but I think it's not really worth it for how much of an edge case this is. To reach this point, you need to be a pretty advanced Yesod user, and reading through #201 should be no problem for you
Closes https://github.com/yesodweb/yesod-scaffold/issues/201
=> Warn that TRUNCATEing many tables with Postgres can become slow
